feat(tooling): init
padok-team/docs-terraform-guidelines pull request #34
Opened 2023-08-18 14:52 UTC by Laudenlaruto

2023-08-22 09:23 UTC, spoukke commented
Should we talk about `tfautomv` in this tooling section?

2023-09-13 13:57 UTC, ChapChap commented
Don't we recommend `terraform_docs` ? `terrascan` ?

2023-10-04 11:45 UTC, cterence requested changes

2023-10-04 11:45 UTC, cterence commented on README.md
> +- [Terraform Pre-commits](terraform/pre-commits.md)
```suggestion
- [Terraform pre-commits](terraform/pre-commits.md)
```

2023-10-04 11:45 UTC, cterence commented on tooling/tflint.md
> +This page goal is to list some useful information about [tflint](https://github.com/terraform-linters/tflint)
```suggestion
The goal of this page is to list some useful information about [tflint](https://github.com/terraform-linters/tflint)
```

2023-10-04 11:45 UTC, cterence commented on tooling/tooling.md
> +# Useful tooling for Terragrunt/Terraform
Shouldn't we rename this to README.md ?

2023-10-04 11:45 UTC, cterence commented on tooling/tooling.md
> +> Left shift as much as possible, security related tasks
```suggestion
> Left shift security related tasks as much as possible
```

2023-10-19 08:54 UTC, cterence approved these changes

2023-11-03 15:11 UTC, merged